# Generated by Django 4.2.20 on 2025-03-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='admin_token',
            field=models.CharField(max_length=16),
        ),
    ]
